version: "2"

linters:
  default: all
  disable:
    - dupl
    - funlen
    - lll
    - gochecknoglobals
    - varnamelen
    - ireturn
    - gomoddirectives
    - godox
    - gocyclo
    - exhaustruct
    - tagliatelle
    - wsl
    # - wsl_v5
    - forbidigo
    - makezero
    - depguard
    - wrapcheck
    - gocritic # does not like log.Fatal with defers
    - godot # comments ending in periods...
    - cyclop # like gocyclo
    - gocognit # like cyclop
    - maintidx # another complexity one
    - errname # base error naming
    - nilnil # inconsistent error returns
    - prealloc # wants to declaring vars with := struct{}
    - nlreturn # wants newline before return, break, and continue (dont want newline before break & continue)
    - exhaustive # some missing switch statements
    - nestif # nested if blocks, complexity issues
    - forcetypeassert # missing some checks, lots of false errors
    - containedctx # some contexts embedded in structs
    - contextcheck # probably worth looking at
    - wastedassign # some interesting assignments, does not like declaring new vars like := ""
    - promlinter # some observability stuff
    - nonamedreturns

  settings:
    goheader:
      values:
        const:
          COMPANY: CTRL IQ, Inc
      template: |-
        SPDX-FileCopyrightText: Copyright (c) {{ YEAR-RANGE }}, {{ COMPANY }}. All rights reserved
        SPDX-License-Identifier: Apache-2.0

  exclusions:
    warn-unused: false
    paths:
      - _test.go
      - testproto/*
